respawn works?
xamionex/NorthstarMods pull request #7
Opened 2022-02-16 03:05 UTC by catornot

look at 
_base_gametype_sp
_savegame

2022-02-16 03:21 UTC, xamionex requested changes
this works

2022-02-16 03:25 UTC, xamionex requested changes

2022-02-16 03:25 UTC, xamionex commented on Northstar.Coop/mod/scripts/vscripts/sp/_base_gametype_sp.gnut
> -				RespawnPlayer( p )
change this from p to player, then it works

2022-02-16 03:34 UTC, catornot commented on Northstar.Coop/mod/scripts/vscripts/sp/_base_gametype_sp.gnut
> -				RespawnPlayer( p )
yeah did the same thing

2022-02-16 03:35 UTC, xamionex commented on Northstar.Coop/mod/scripts/vscripts/sp/_base_gametype_sp.gnut
> -				RespawnPlayer( p )
> yeah did the same thing

yeye but commit so i can do PR

2022-02-16 12:43 UTC, catornot commented
I think everything is ready for a merge.

2022-02-16 13:11 UTC, catornot commented on Northstar.Coop/mod/scripts/vscripts/sp/_base_gametype_sp.gnut
> -				RespawnPlayer( p )
Why is the line being removed? 
We need it right?

2022-02-17 03:05 UTC, catornot commented
I will make another pr tmr If I even get it working.
this one isn't going to work.

2022-02-17 03:05 UTC, closed without merging